name: Zephyr ESP32 Wroom DevkitC Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: .
          toolchains: xtensa-esp32-elf

      - name: Fetch Espressif HAL blobs
        run: west blobs fetch hal_espressif

      - name: Build application
        run: west build -b  esp32_devkitc/esp32/procpu -p -- -DSSID="DUMMY_SSID" -DPSK="DUMMY_PSK"
